### ISSUE TITLE
Support for Smallworld 4.x?

### ISSUE THREAD

**Issue by hetsch** [siamz/smallworld-magik-vscode#14]
Just a quick question. Is Smallworld 4.x supported, or can you think of any workaround to get the extension running with this older version?

Thank's a lot!

**Comment by siamz** [comment]
Please contact paride (paride.giovacchini@gmail.com) who has forked this extension with support for Smallworld 4.x.

**Comment by siamz** [comment]
This extension doesn't support Smallworld 4.x sessions, but you can contact paride (paride.giovacchini@gmail.com) who has forked this extension with support for Smallworld 4.x.

**Comment by hetsch** [comment]
Thank you for your help. I've contacted Paride and hope to get an answer soon!
