### ISSUE TITLE
Unable to open powershell

### ISSUE THREAD

**Issue by MarkerDave** [siamz/smallworld-magik-vscode#6]
With version 1.2.0 when trying to start a new session, sometimes vsCode gives the error that it is unable to open powershell. 
This happens when there is already any kind of terminal open in vsCode.
After Closing all terminals in vsCode it is possible again to start a smallworld session.

**Comment by Systemap** [comment]
Thanks **MarkerDave** for reporting the release 1.2.0 occasional VSCode Error “unable to open powershell” on starting a session. The Smallworld 5 session is managed by VSCode Terminal object that simplifies the communication to the session for code compiling. This creates a Command shell inside the VSCode default integrated Terminal, which if set to PowerShell this error happens.  
I will list this as a known issue for 1.2.0.

**Comment by alexhenriquepv** [comment]
I found a problem. When I start a session, the compiler executes an external terminal. What's wrong??
![image](https://user-images.githubusercontent.com/12400276/60227006-f91b2200-9863-11e9-818c-07c4885c18e1.png)

**Comment by Systemap** [comment]
The integrated terminal, code compiling and aporpos hover actions are only available for Smallworld Version 5.x.

**Comment by alexhenriquepv** [comment]
Ok. Thanks for the response.
I will work to resolve this problem. 😁

Em sex, 28 de jun de 2019 00:01, SiamZ <notifications@github.com> escreveu:

**Comment by Systemap** [comment]
That would be great. The code to connect to a session is all in src\swSessions.js, specifically check_gisExec() and runaliases() functions.
